apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: harbor.xylink.com:8081/xylink/2021.05.17:v1
        name: mynginx
        ports:
        - containerPort: 80
